<!DOCTYPE html>
<html lang="en">

<head>
 
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Quantum Digiadmin</title>

    <!-- Bootstrap Core CSS -->
    <link href="<?php echo base_url(); ?>public/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="<?php echo base_url(); ?>public/css/my2.css">

    <!-- Custom Fonts -->
    <link href="<?php echo base_url(); ?>public/vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    
 <!--
    <link href='https://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Kaushan+Script' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Droid+Serif:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700' rel='stylesheet' type='text/css'>
 -->

    <!-- Theme CSS & topbar-->
    <link href="<?php echo base_url(); ?>public/css/agency.min.css" rel="stylesheet">


</head>

<body id="page-top" class="index"><p style="margin: 0cm;font-size:13px;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: normal;text-align: start;text-indent: 0px;text-decoration: none;line-height: 12pt;vertical-align: baseline;"><strong><span style="color: rgb(51, 51, 51);">Privacy Policy</span></strong></p>
<p style="margin: 0cm;font-size:13px;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: normal;text-align: start;text-indent: 0px;text-decoration: none;line-height: 12pt;vertical-align: baseline;"><strong><span style="color: rgb(51, 51, 51);">Introduction</span></strong></p>
<p style="margin: 0cm;font-size:13px;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: normal;text-align: start;text-indent: 0px;text-decoration: none;vertical-align: baseline;"><span style="color: rgb(102, 102, 102);">Quantum Solutions Pte Ltd. (&ldquo;Quantum Solutions&rdquo;, &ldquo;we&rdquo;, &ldquo;us&rdquo;) takes the privacy of your information seriously. This Privacy Policy applies to the quantumcs.com website (the &ldquo;quantumcs.com&rdquo;) and governs data collection, processing, usage in compliance with the Personal Data Protection Act 2012 (No. 26 of 2012) of Singapore (&ldquo;PDPA&rdquo;). By using the website, you consent to the data practices described in this statement. Capitalized terms that are not defined in this Privacy Policy have the meaning given to them in our Terms of Service.&nbsp;</span></p>
<p style="margin: 0cm;font-size:13px;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: normal;text-align: start;text-indent: 0px;text-decoration: none;">&nbsp;</p>
<p style="margin: 0cm;font-size:13px;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: normal;text-align: start;text-indent: 0px;text-decoration: none;line-height: 12pt;vertical-align: baseline;"><strong><span style="color: rgb(51, 51, 51);">Information Collected From All Visitors To Our Website</span></strong></p>
<p style="margin: 0cm;font-size:13px;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: normal;text-align: start;text-decoration: none;text-indent: -18pt;line-height: 19.5pt;vertical-align: baseline;">a.<span style='font-style: normal;font-weight: normal;font-size:9px;line-height: normal;font-family: "Times New Roman";'>&nbsp; &nbsp; &nbsp; &nbsp;</span><span style="color: rgb(102, 102, 102);">Consent Required Quantum Consumer Solutions Pte Ltd&nbsp;will not collect, use or disclose your personal data unless:</span></p>
<p style="margin: 0cm;font-size:13px;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: normal;text-align: start;text-decoration: none;text-indent: -18pt;line-height: 19.5pt;vertical-align: baseline;"><span style="font-family: Symbol;">&middot;<span style='font-style: normal;font-weight: normal;font-size:9px;line-height: normal;font-family: "Times New Roman";'>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</span></span><span style="color: rgb(102, 102, 102);">you give, or are deemed to give, consent to the collection, use or disclosure of your personal data; or</span></p>
<p style="margin: 0cm;font-size:13px;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: normal;text-align: start;text-decoration: none;text-indent: -18pt;line-height: 19.5pt;vertical-align: baseline;"><span style="font-family: Symbol;">&middot;<span style='font-style: normal;font-weight: normal;font-size:9px;line-height: normal;font-family: "Times New Roman";'>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</span></span><span style="color: rgb(102, 102, 102);">the collection, use or disclosure of your personal data without your consent is required or authorized under the PDPA or other written law.</span></p>
<p style="margin: 0cm;font-size:13px;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: normal;text-align: start;text-indent: 0px;text-decoration: none;line-height: 19.5pt;vertical-align: baseline;"><span style="color: rgb(102, 102, 102);">If you disclose the personal data of third parties to Quantum Consumer Solutions Pte Ltd, you represent that you have obtained the consent of the relevant third parties to have their personal data collected, used and/or disclosed by Quantum Consumer Solutions Pte Ltd for the applicable purposes listed in clause 1.</span></p>
<p style="margin: 0cm;font-size:13px;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: normal;text-align: start;text-decoration: none;text-indent: -18pt;line-height: 19.5pt;vertical-align: baseline;">b.<span style='font-style: normal;font-weight: normal;font-size:9px;line-height: normal;font-family: "Times New Roman";'>&nbsp; &nbsp; &nbsp; &nbsp;</span><span style="color: rgb(102, 102, 102);">Provision of Consent Quantum Consumer Solutions Pte Ltd &nbsp;will not obtain or attempt to obtain your consent for collecting, using or disclosing personal data by providing false or misleading information with respect to the collection, use or disclosure of your personal data.</span></p>
<p style="margin: 0cm;font-size:13px;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: normal;text-align: start;text-decoration: none;text-indent: -18pt;line-height: 19.5pt;vertical-align: baseline;">c.<span style='font-style: normal;font-weight: normal;font-size:9px;line-height: normal;font-family: "Times New Roman";'>&nbsp; &nbsp; &nbsp; &nbsp;&nbsp;</span><span style="color: rgb(102, 102, 102);">Withdrawal of Consent</span></p>
<p style="margin: 0cm;font-size:13px;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: normal;text-align: start;text-decoration: none;text-indent: -18pt;line-height: 19.5pt;vertical-align: baseline;"><span style="font-family: Symbol;">&middot;<span style='font-style: normal;font-weight: normal;font-size:9px;line-height: normal;font-family: "Times New Roman";'>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</span></span><span style="color: rgb(102, 102, 102);">You may at any time withdraw your consent for any of the purposes which you have previously consented to by providing us with notice through a request submitted to the Data Protection Officer in writing or via the email at the content details provided below.</span></p>
<p style="margin: 0cm;font-size:13px;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: normal;text-align: start;text-decoration: none;text-indent: -18pt;line-height: 19.5pt;vertical-align: baseline;"><span style="font-family: Symbol;">&middot;<span style='font-style: normal;font-weight: normal;font-size:9px;line-height: normal;font-family: "Times New Roman";'>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</span></span><span style="color: rgb(102, 102, 102);">Please be aware that once we receive confirmation that you wish to withdraw your consent, it may take up to ten (10) working days for your withdrawal to be reflected in our systems. During this period of time, your personal data will continue to be collected, used and/or disclosed pursuant to the purposes set out at clause 3 above.</span></p>
<p style="margin: 0cm;font-size:13px;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: normal;text-align: start;text-decoration: none;text-indent: -18pt;line-height: 19.5pt;vertical-align: baseline;"><span style="font-family: Symbol;">&middot;<span style='font-style: normal;font-weight: normal;font-size:9px;line-height: normal;font-family: "Times New Roman";'>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</span></span><span style="color: rgb(102, 102, 102);">On receipt of such notice, Quantum Consumer Solutions Pte Ltd will inform you of the likely consequences of withdrawing your consent and we may no longer be in a position to continue to provide our services to you. Such a withdrawal may therefore result in the termination of any relationship that you may have with us.</span></p>
<p style="margin: 0cm;font-size:13px;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: normal;text-align: start;text-decoration: none;text-indent: -18pt;line-height: 19.5pt;vertical-align: baseline;"><span style="font-family: Symbol;">&middot;<span style='font-style: normal;font-weight: normal;font-size:9px;line-height: normal;font-family: "Times New Roman";'>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</span></span><span style="color: rgb(102, 102, 102);">At the same time, it should be noted that your withdrawal of consent will not prevent us from exercising our legal rights (including any remedies, or undertaking any steps as we may be entitled to by law).</span></p>
<p style="margin: 0cm;font-size:13px;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: normal;text-align: start;text-decoration: none;text-indent: -18pt;line-height: 19.5pt;vertical-align: baseline;"><span style="font-family: Symbol;">&middot;<span style='font-style: normal;font-weight: normal;font-size:9px;line-height: normal;font-family: "Times New Roman";'>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</span></span><span style="color: rgb(102, 102, 102);">The withdrawal of consent in itself may not result in the deletion or destroying of your personal data. Any retention of data will be based on Quantum Consumer Solutions Pte Ltd&rsquo;s business needs as deemed legitimate under the PDPA provisions.</span></p>
<p style="margin: 0cm;font-size:13px;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: normal;text-align: start;text-indent: 0px;text-decoration: none;">&nbsp;</p>
<h5 style="margin: 0cm;font-size:13px;font-family: Calibri, sans-serif;font-weight: bold;color: rgb(0, 0, 0);font-style: normal;text-align: start;text-indent: 0px;text-decoration: none;line-height: 12pt;vertical-align: baseline;"><span style="color: rgb(51, 51, 51);">Information Collected From Registered Users of Our Website</span></h5>
<p style="color: rgb(0, 0, 0);font-family: Calibri;font-size: 14px;font-style: normal;font-weight: normal;text-align: start;text-indent: 0px;text-decoration: none;margin: 0cm;vertical-align: baseline; border-box;outline: 0px;"><span style="font-size:13px;color: rgb(102, 102, 102);">Quantum Consumer Solutions Pte Ltd&nbsp;will take reasonable steps to make sure that the personal data it collects, uses or discloses is accurate, complete and up to date.We generally rely on personal data provided by you (or your authorised representative). In order to ensure that your personal data is current, complete and accurate, please update us if there are any changes to your personal data by informing our Data Protection Officer in writing or via the email at the content details provided below.</span></p>
<p style="margin: 0cm;font-size:13px;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: normal;text-align: start;text-indent: 0px;text-decoration: none;">&nbsp;</p>
<p style="margin: 0cm;font-size:13px;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: normal;text-align: start;text-indent: 0px;text-decoration: none;line-height: 12pt;vertical-align: baseline;"><strong><span style="color: rgb(51, 51, 51);">Disclosure of Personal Information</span></strong></p>
<p style="margin: 0cm;font-size:13px;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: normal;text-align: start;text-indent: 0px;text-decoration: none;vertical-align: baseline;"><span style="color: rgb(102, 102, 102);">In providing Quantum Consumer Solutions Pte Ltd with your personal data (either directly or through a third party), you hereby agree that Quantum Consumer Solutions Pte Ltd&nbsp;may collect, store, process, disclose, access, review and/or use personal data (including sensitive personal data) about you, whether obtained from you or from other sources (such as our Approved Training Organisations), for the purposes set out below and/or any other administrative or operational purposes and/or the purpose of managing your relationship with Quantum Consumer Solutions Pte Ltd:</span></p>
<p style="margin: 0cm;font-size:13px;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: normal;text-align: start;text-decoration: none;text-indent: -18pt;line-height: 19.5pt;vertical-align: baseline;"><span style="font-family: Symbol;">&middot;<span style='font-style: normal;font-weight: normal;font-size:9px;line-height: normal;font-family: "Times New Roman";'>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</span></span><span style="color: rgb(102, 102, 102);">- providing services to you in relation to your transactions with Quantum Consumer Solutions Pte Ltd;</span></p>
<p style="margin: 0cm;font-size:13px;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: normal;text-align: start;text-decoration: none;text-indent: -18pt;line-height: 19.5pt;vertical-align: baseline;"><span style="font-family: Symbol;">&middot;<span style='font-style: normal;font-weight: normal;font-size:9px;line-height: normal;font-family: "Times New Roman";'>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</span></span><span style="color: rgb(102, 102, 102);">- verification and identification purposes, including verifying your identity when you attend the assessments conducted by Quantum Consumer Solutions Pte Ltd;</span></p>
<p style="margin: 0cm;font-size:13px;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: normal;text-align: start;text-decoration: none;text-indent: -18pt;line-height: 19.5pt;vertical-align: baseline;"><span style="font-family: Symbol;">&middot;<span style='font-style: normal;font-weight: normal;font-size:9px;line-height: normal;font-family: "Times New Roman";'>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</span></span><span style="color: rgb(102, 102, 102);">- enabling the Police Licensing Regulatory Department to carry out the necessary licensing for the private security industry;</span></p>
<p style="margin: 0cm;font-size:13px;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: normal;text-align: start;text-decoration: none;text-indent: -18pt;line-height: 19.5pt;vertical-align: baseline;"><span style="font-family: Symbol;">&middot;<span style='font-style: normal;font-weight: normal;font-size:9px;line-height: normal;font-family: "Times New Roman";'>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</span></span><span style="color: rgb(102, 102, 102);">- assisting you with your job placement and security clearances when you engage our Business &amp; Employment Services Division;</span></p>
<p style="margin: 0cm;font-size:13px;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: normal;text-align: start;text-decoration: none;text-indent: -18pt;line-height: 19.5pt;vertical-align: baseline;"><span style="font-family: Symbol;">&middot;<span style='font-style: normal;font-weight: normal;font-size:9px;line-height: normal;font-family: "Times New Roman";'>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</span></span><span style="color: rgb(102, 102, 102);">- processing your request for a loan or fixed deposit when you approach our Financial Services Division;</span></p>
<p style="margin: 0cm;font-size:13px;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: normal;text-align: start;text-decoration: none;text-indent: -18pt;line-height: 19.5pt;vertical-align: baseline;"><span style="font-family: Symbol;">&middot;<span style='font-style: normal;font-weight: normal;font-size:9px;line-height: normal;font-family: "Times New Roman";'>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</span></span><span style="color: rgb(102, 102, 102);">- enabling your use of the services which Quantum Consumer Solutions Pte Ltd&nbsp;provides, including, where necessary, contacting you (whether by SMS, email or otherwise);</span></p>
<p style="margin: 0cm;font-size:13px;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: normal;text-align: start;text-decoration: none;text-indent: -18pt;line-height: 19.5pt;vertical-align: baseline;"><span style="font-family: Symbol;">&middot;<span style='font-style: normal;font-weight: normal;font-size:9px;line-height: normal;font-family: "Times New Roman";'>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</span></span><span style="color: rgb(102, 102, 102);">- evaluative purposes, including processing your job application pursuant to Quantum Consumer Solutions Pte Ltd&rsquo;s recruitment activities;</span></p>
<p style="margin: 0cm;font-size:13px;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: normal;text-align: start;text-decoration: none;text-indent: -18pt;line-height: 19.5pt;vertical-align: baseline;"><span style="font-family: Symbol;">&middot;<span style='font-style: normal;font-weight: normal;font-size:9px;line-height: normal;font-family: "Times New Roman";'>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</span></span><span style="color: rgb(102, 102, 102);">- enabling your participation in our lucky draws/contests;</span></p>
<p style="margin: 0cm;font-size:13px;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: normal;text-align: start;text-decoration: none;text-indent: -18pt;line-height: 19.5pt;vertical-align: baseline;"><span style="font-family: Symbol;">&middot;<span style='font-style: normal;font-weight: normal;font-size:9px;line-height: normal;font-family: "Times New Roman";'>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</span></span><span style="color: rgb(102, 102, 102);">- processing your payment/interest/reservation of retail items with us;</span></p>
<p style="margin: 0cm;font-size:13px;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: normal;text-align: start;text-decoration: none;text-indent: -18pt;line-height: 19.5pt;vertical-align: baseline;"><span style="font-family: Symbol;">&middot;<span style='font-style: normal;font-weight: normal;font-size:9px;line-height: normal;font-family: "Times New Roman";'>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</span></span><span style="color: rgb(102, 102, 102);">- dealing with enquiries made by you;</span></p>
<p style="margin: 0cm;font-size:13px;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: normal;text-align: start;text-decoration: none;text-indent: -18pt;line-height: 19.5pt;vertical-align: baseline;"><span style="font-family: Symbol;">&middot;<span style='font-style: normal;font-weight: normal;font-size:9px;line-height: normal;font-family: "Times New Roman";'>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</span></span><span style="color: rgb(102, 102, 102);">- maintenance and updating of the data;</span></p>
<p style="margin: 0cm;font-size:13px;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: normal;text-align: start;text-decoration: none;text-indent: -18pt;line-height: 19.5pt;vertical-align: baseline;"><span style="font-family: Symbol;">&middot;<span style='font-style: normal;font-weight: normal;font-size:9px;line-height: normal;font-family: "Times New Roman";'>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</span></span><span style="color: rgb(102, 102, 102);">- administrative or operational purposes;</span></p>
<p style="margin: 0cm;font-size:13px;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: normal;text-align: start;text-decoration: none;text-indent: -18pt;line-height: 19.5pt;vertical-align: baseline;"><span style="font-family: Symbol;">&middot;<span style='font-style: normal;font-weight: normal;font-size:9px;line-height: normal;font-family: "Times New Roman";'>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</span></span><span style="color: rgb(102, 102, 102);">- tax filing preparation;</span></p>
<p style="margin: 0cm;font-size:13px;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: normal;text-align: start;text-decoration: none;text-indent: -18pt;line-height: 19.5pt;vertical-align: baseline;"><span style="font-family: Symbol;">&middot;<span style='font-style: normal;font-weight: normal;font-size:9px;line-height: normal;font-family: "Times New Roman";'>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</span></span><span style="color: rgb(102, 102, 102);">- processing credit notes and processing refunds;</span></p>
<p style="margin: 0cm;font-size:13px;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: normal;text-align: start;text-decoration: none;text-indent: -18pt;line-height: 19.5pt;vertical-align: baseline;"><span style="font-family: Symbol;">&middot;<span style='font-style: normal;font-weight: normal;font-size:9px;line-height: normal;font-family: "Times New Roman";'>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</span></span><span style="color: rgb(102, 102, 102);">- collection of fees, charges and expenses for services provided;</span></p>
<p style="margin: 0cm;font-size:13px;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: normal;text-align: start;text-decoration: none;text-indent: -18pt;line-height: 19.5pt;vertical-align: baseline;"><span style="font-family: Symbol;">&middot;<span style='font-style: normal;font-weight: normal;font-size:9px;line-height: normal;font-family: "Times New Roman";'>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</span></span><span style="color: rgb(102, 102, 102);">- facilitating the making and payment of claims, including payments by cheque, bank transfers or other means;</span></p>
<p style="margin: 0cm;font-size:13px;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: normal;text-align: start;text-decoration: none;text-indent: -18pt;line-height: 19.5pt;vertical-align: baseline;"><span style="font-family: Symbol;">&middot;<span style='font-style: normal;font-weight: normal;font-size:9px;line-height: normal;font-family: "Times New Roman";'>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</span></span><span style="color: rgb(102, 102, 102);">- carrying out billing, accounting, auditing and the maintenance of proper book-keeping to explain Quantum Consumer Solutions Pte Ltd&nbsp;operations and business;</span></p>
<p style="margin: 0cm;font-size:13px;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: normal;text-align: start;text-decoration: none;text-indent: -18pt;line-height: 19.5pt;vertical-align: baseline;"><span style="font-family: Symbol;">&middot;<span style='font-style: normal;font-weight: normal;font-size:9px;line-height: normal;font-family: "Times New Roman";'>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</span></span><span style="color: rgb(102, 102, 102);">- the disclosure of the relevant books, documents, records and information (in hard or soft copy) to the auditors for the preparation of financial reports; and/or the disclosure of the relevant books, documents, records and information (in hard or soft copy) to the relevant government authorities pursuant to any written law.</span></p>
<p style="margin: 0cm;font-size:13px;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: normal;text-align: start;text-indent: 0px;text-decoration: none;vertical-align: baseline;"><span style="color: rgb(102, 102, 102);">You further agree to be bound by the prevailing terms of this DPP as updated from time to time.</span></p>
<p style="margin: 0cm;font-size:13px;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: normal;text-align: start;text-indent: 0px;text-decoration: none;vertical-align: baseline;"><span style="color: rgb(102, 102, 102);">&nbsp;</span></p>
<h5 style="margin: 0cm;font-size:13px;font-family: Calibri, sans-serif;font-weight: bold;color: rgb(0, 0, 0);font-style: normal;text-align: start;text-indent: 0px;text-decoration: none;line-height: 12pt;vertical-align: baseline;"><span style="color: rgb(51, 51, 51);">Security of Personal Information</span></h5>
<p style="color: rgb(0, 0, 0);font-family: Calibri;font-size: 14px;font-style: normal;font-weight: normal;text-align: start;text-indent: 0px;text-decoration: none;margin: 0cm;vertical-align: baseline; border-box;outline: 0px;"><span style="font-size:13px;color: rgb(102, 102, 102);">To safeguard your personal data from unauthorised access, collection, use, copying, modification, disclosure, disposal or similar risks, Quantum Consumer Solutions Pte Ltd takes appropriate administrative, physical and technical measures.You should be aware, however, that no method of transmission over the Internet or method of electronic storage is completely secure. While security cannot be guaranteed, we strive to protect the security of your information and are constantly reviewing and enhancing our information security measures. Quantum Consumer Solutions Pte Ltd will not keep personal data for longer than is necessary to fulfil the purpose for which it was collected, or as required or permitted by applicable laws, and will take reasonable steps to securely dispose of personal data if it is no longer needed.</span></p>
<p style="color: rgb(0, 0, 0);font-family: Calibri;font-size: 14px;font-style: normal;font-weight: normal;text-align: start;text-indent: 0px;text-decoration: none;margin: 0cm;vertical-align: baseline; border-box;outline: 0px;"><span style="font-size:13px;color: rgb(102, 102, 102);">&nbsp;</span></p>
<p style="color: rgb(0, 0, 0);font-family: Calibri;font-size: 14px;font-style: normal;font-weight: normal;text-align: start;text-indent: 0px;text-decoration: none;margin: 0cm;vertical-align: baseline; border-box;outline: 0px;"><span style="font-size:13px;color: rgb(102, 102, 102);">Cookies are simple text files which are stored on your computer or mobile device by our website&rsquo;s server. Only Quantum Consumer Solutions Pte Ltd&rsquo;s server will be able to retrieve or read the contents of these cookies. Quantum Consumer Solutions Pte Ltd&nbsp;uses cookies on its website in order to enable certain features and functionality, to ensure a smooth and optimised user experience, and to improve user security.</span></p>
<p style="margin: 0cm;font-size:13px;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: normal;text-align: start;text-indent: 0px;text-decoration: none;vertical-align: baseline;"><span style="color: rgb(102, 102, 102);">&nbsp;</span></p>
<h5 style="margin: 0cm;font-size:13px;font-family: Calibri, sans-serif;font-weight: bold;color: rgb(0, 0, 0);font-style: normal;text-align: start;text-indent: 0px;text-decoration: none;line-height: 12pt;vertical-align: baseline;"><span style="color: rgb(51, 51, 51);">Links to Other Websites</span></h5>
<p style="color: rgb(0, 0, 0);font-family: Calibri;font-size: 14px;font-style: normal;font-weight: normal;text-align: start;text-indent: 0px;text-decoration: none;margin: 0cm;vertical-align: baseline; border-box;outline: 0px;"><span style="font-size:13px;color: rgb(102, 102, 102);">We generally do not transfer your personal data to countries or territories outside of Singapore. However, if we do so, for instance, if your personal data is required to be transferred for administrative or operational purposes by Quantum Consumer Solutions Pte Ltd, we will ensure that the recipients thereof provide a standard of protection to your personal data so transferred that is comparable to that which is provided herein.</span></p>
<p style="margin: 0cm;font-size:13px;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: normal;text-align: start;text-indent: 0px;text-decoration: none;vertical-align: baseline;"><span style="color: rgb(102, 102, 102);">&nbsp;</span></p>
<h5 style="margin: 0cm;font-size:13px;font-family: Calibri, sans-serif;font-weight: bold;color: rgb(0, 0, 0);font-style: normal;text-align: start;text-indent: 0px;text-decoration: none;line-height: 12pt;vertical-align: baseline;"><span style="color: rgb(51, 51, 51);">Further Contact Information</span></h5>
<p style="color: rgb(0, 0, 0);font-family: Calibri;font-size: 14px;font-style: normal;font-weight: normal;text-align: start;text-indent: 0px;text-decoration: none;margin: 0cm;vertical-align: baseline; border-box;outline: 0px;"><span style="font-size:13px;color: rgb(102, 102, 102);">Quantum Consumer Solutions Pte Ltd has designated a Data Protection Officer who will be responsible for ensuring Quantum Consumer Solutions Pte Ltd&rsquo;s compliance with applicable data protection laws. If you have any queries or requests or wish to make any applications concerning your personal information or data, please contact the Data Protection Officer:</span></p>
<p style="color: rgb(0, 0, 0);font-family: Calibri;font-size: 14px;font-style: normal;font-weight: normal;text-align: start;text-indent: 0px;text-decoration: none;margin: 0cm;vertical-align: baseline; border-box;outline: 0px;"><strong><span style="font-size:13px;font-family: Calibri, sans-serif;color: rgb(102, 102, 102);border: 1pt none windowtext;padding: 0cm;font-weight: normal;">Contact Person: Data Protection Officer</span></strong><span style="font-size:13px;color: rgb(102, 102, 102);border: 1pt none windowtext;padding: 0cm;"><br><strong><span style="font-family: Calibri, sans-serif;font-weight: normal;">Email:&nbsp;</span></strong></span><span style="font-size:13px;"><a contenteditable="false" href="mailto:admin@quantumcs.com" style="color: rgb(248, 72, 28) !important;text-decoration: underline;" title="mailto:admin@quantumcs.com"><span style="border: 1pt none windowtext;padding: 0cm;">admin@quantumcs.com</span></a></span><span style="font-size:13px;color: rgb(102, 102, 102);border: 1pt none windowtext;padding: 0cm;"><br><strong><span style="font-family: Calibri, sans-serif;font-weight: normal;">Address: 78 Shenton Way, #05-01, Singapore 079120</span></strong></span></p>
<p style="color: rgb(0, 0, 0);font-family: Calibri;font-size: 14px;font-style: normal;font-weight: normal;text-align: start;text-indent: 0px;text-decoration: none;margin: 0cm;vertical-align: baseline; border-box;outline: 0px;"><em><span style="font-size:13px;font-family: Calibri, sans-serif;color: rgb(102, 102, 102);border: 1pt none windowtext;padding: 0cm;font-style: normal;">Please note that if your personal data has been provided to us by a third party, you should contact such party directly to make any queries, feedback, and access and correction requests.</span></em></p>
<p style="margin: 0cm;font-size:13px;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: normal;text-align: start;text-indent: 0px;text-decoration: none;vertical-align: baseline;"><span style="color: rgb(102, 102, 102);">&nbsp;</span></p>
</body>

</html>